### ISSUE TITLE
c2ffi fails due to '-F' flag

### ISSUE THREAD

**Issue by shelvick** [borodust/claw#11]
On my machine, claw is attempting to run c2ffi like this:
```
c2ffi /tmp/sometmpfile -D null -M /tmp/anothertmpfile --lang c -A x86_64-pc-linux-gnu [-i lots of includes ...] -F wrapper-pathname 
```
However the latest c2ffi (version 14) barfs on the `-F` flag and does not seem to support it, or at least it is not documented. What is the purpose of that flag?

**Comment by borodust** [comment]
I don't quite remember -`claw` dropped `c2ffi` long ago. Although, `quicklisp` probably still uses [outdated](https://github.com/borodust/claw-legacy) version of `claw`.

**Comment by shelvick** [comment]
Ah, alright, I mistakenly thought QL had the most updated version. Thanks!
