### ISSUE TITLE
Error compiling iffi

### ISSUE THREAD

**Issue by Linden6** [borodust/claw#2]
Compiling iffi fails with the message:
```
;;; Error:
;;;   in file iffi.lisp, position 295
;;;   at (INITIALIZE-IFFI)
;;;   * The macro form (CFFI:DEFCFUN ("aligned_alloc" ALIGNED-ALLOC) :POINTER (BYTE-ALIGNMENT :SIZE) (BYTE-SIZE :SIZE)) was not expanded successfully.
;;; Error detected:
;;; Unknown CFFI type :SIZE
Condition of type: COMPILE-FILE-ERROR
```

As :SIZE is a foreign type built into CFFI, I'm not sure why this is happening, although - having said that - I'm not too experienced in these matters.

This is on ECL, (the only other implementation that I currently have installed that isn't SBCL).

**Comment by borodust** [comment]
This should help:
```lisp
(ql:update-all-dists)
```

**Comment by Linden6** [comment]
That did the trick - thanks again!
