### ISSUE TITLE
Undefined Function Error

### ISSUE THREAD

**Issue by JosephBoyd** [borodust/claw#8]
I get the following when running (ql:quickload :claw-olm/wrapper) and (claw:load-wrapper :claw-olm/wrapper)

The alien function "resect_options_enforce_definition" is undefined.
   [Condition of type SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR]\

I get the same error when trying to load claw-torch.

**Comment by borodust** [comment]
`resect_options_enforce_definition` is a latest addition to [`libresect`](https://github.com/borodust/libresect/). You need to rebuilt that library.

**Comment by JosephBoyd** [comment]
Yes, that worked, thanks!
